name: Tests
on: 
  pull_request:
    branches: 
      - main
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest] # macos-latest is not supported by docker/setup-buildx-action
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - name: Git Clone Local Repo
        run: git clone https://github.com/matter-labs/local-setup
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Run Docker Compose Daemon
        run: cd local-setup && mkdir -p ./volumes && mkdir -p ./volumes/postgres ./volumes/geth ./volumes/zksync/env/dev ./volumes/zksync/data && touch ./volumes/zksync/env.env && docker compose up -d && cd ..
      - name: Wait for Docker containers to start
        run: sleep 300
      - name: Print Docker logs
        run: cd local-setup && docker compose logs && cd ..
      - name: Run tests
        run: docker ps && yarn test
